In [2]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print("Setup complete.")

Setup complete.


1.
In the cell below, create a DataFrame fruits that looks like this:

Image

In [3]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})

# Check your answer
fruits

   Apples  Bananas
0      30       21

2.
Create a dataframe fruit_sales that matches the diagram below:

Image

In [4]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = pd.DataFrame({'Apples': [35,41], 'Bananas': [21,34]}, index=['2017 Sales', '2018 Sales'])

# Check your answer
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

3.
Create a variable ingredients with a Series that looks like:

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [5]:
ingredients =  pd.Series(['4 cups', '1 cup', '2 large', '1 can'], name='Dinner', index=['Flour', 'Milk', 'Eggs', 'Spam'])

# Check your answer
#q3.check()
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: str